version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@web/test-runner"
    versions:
    - 0.12.20
  - dependency-name: "@esm-bundle/chai"
    versions:
    - 4.3.1
